name: Build docker images

on:
  push:
    branches: [ "main", "cicd" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    #build acts-util-core
    - name: Checkout ACTS-Util repo
      uses: actions/checkout@v4
      with:
        repository: aczwink/ACTS-Util
        path: actsutil

    - name: Building acts-util-core
      run: |
        npm install
        npm run compile
        npm link
      working-directory: ./actsutil/core

    #build acts-util-node
    - name: Building acts-util-node
      run: |
        npm link acts-util-core
        npm install
        npm run build
        npm link
      working-directory: ./actsutil/node

    #build acts-util-apilib
    - name: Building acts-util-apilib
      run: |
        npm link acts-util-core acts-util-node
        npm install
        npm run build
        npm link
      working-directory: ./actsutil/apilib

    #build oidp
    - uses: actions/checkout@v4
    
    - name: Build oidp
      run: |
        npm install
      working-directory: ./oidp

    #publish images      
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./oidp
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/aczwink/openidentityprovider:latest
