#!/bin/sh
FORMAT='window.process = { env: {OIDP_AUTH_ENDPOINT:"%s",OIDP_BACKEND:"%s",OIDP_BACKEND_PORT:"%s",OIDP_ENDSESSION_ENDPOINT:"%s",OIDP_FRONTEND_BASEURL:"%s",OIDP_TOKEN_ENDPOINT:"%s"} };\n'
printf "$FORMAT" "$OIDP_AUTH_ENDPOINT" "$OIDP_BACKEND" "$OIDP_BACKEND_PORT" "$OIDP_ENDSESSION_ENDPOINT" "$OIDP_FRONTEND_BASEURL" "$OIDP_TOKEN_ENDPOINT" > /var/www/html/env.js